### ISSUE TITLE
Container build failed

### ISSUE THREAD

**Issue by wuffo** [PiotrCzapla/vscode-wordpress#1]
Attempts to create the container fail on with the following relevant bit of the creation log. On codespaces. Thanks for any help.

```
2022-07-05 22:53:50.157Z: #11 [ 6/10] RUN cd /tmp && 	git clone git://github.com/xdebug/xdebug.git &&     	cd xdebug && 	git checkout xdebug_3_0 && 	phpize && 	./configure --enable-xdebug && 	make && 	make install &&     rm -rf /tmp/xdebug ;     { 	echo 'zend_extension=xdebug.so'; 	echo 'xdebug.mode=debug'; 	echo 'xdebug.client_port=9003'; 	echo 'xdebug.start_with_request = yes';   } > /usr/local/etc/php/conf.d/xdebug.ini;     docker-php-ext-enable xdebug;
2022-07-05 22:53:50.169Z: #11 sha256:cdf98e1d3a0811aea1f0e40397538dcc240ab317ade328082ad8ab162435e630
2022-07-05 22:53:50.363Z: #11 0.540 Cloning into 'xdebug'...
2022-07-05 22:56:01.317Z: #11 131.5 fatal: unable to connect to github.com:
2022-07-05 22:56:01.332Z: #11 131.5 github.com[0: 192.30.255.112]: errno=Connection timed out
2022-07-05 22:56:01.348Z: #11 131.5 
2022-07-05 22:56:01.457Z: #11 131.5 [05-Jul-2022 22:56:01 UTC] PHP Warning:  Failed loading Zend extension 'xdebug.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so (/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so: cannot open shared object file: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so.so (/usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
2022-07-05 22:56:01.475Z: #11 131.5 error: 'xdebug' does not exist
2022-07-05 22:56:01.491Z: #11 131.5 
2022-07-05 22:56:01.506Z: #11 131.5 usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
2022-07-05 22:56:01.538Z: #11 131.5    ie: /usr/local/bin/docker-php-ext-enable gd mysqli
2022-07-05 22:56:01.553Z: #11 131.5        /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
2022-07-05 22:56:01.579Z: #11 131.5        /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc
2022-07-05 22:56:01.596Z: #11 131.5 
2022-07-05 22:56:01.619Z: #11 131.5 Possible values for module-name:
2022-07-05 22:56:01.636Z: #11 131.5 bcmath.so exif.so gd.so imagick.so mysqli.so opcache.so sodium.so zip.so
2022-07-05 22:56:01.654Z: #11 131.5 
2022-07-05 22:56:01.683Z: #11 131.5 Some of the above modules are already compiled into PHP; please check
2022-07-05 22:56:01.711Z: #11 131.5 the output of "php -i" to see which modules are already loaded.
2022-07-05 22:56:01.728Z: #11 ERROR: executor failed running [/bin/sh -c cd /tmp && 	git clone git://github.com/xdebug/xdebug.git &&     	cd xdebug && 	git checkout xdebug_3_0 && 	phpize && 	./configure --enable-xdebug && 	make && 	make install &&     rm -rf /tmp/xdebug ;     { 	echo 'zend_extension=xdebug.so'; 	echo 'xdebug.mode=debug'; 	echo 'xdebug.client_port=9003'; 	echo 'xdebug.start_with_request = yes';   } > /usr/local/etc/php/conf.d/xdebug.ini;     docker-php-ext-enable xdebug;]: exit code: 1
2022-07-05 22:56:01.745Z: ------
2022-07-05 22:56:01.763Z:  > [ 6/10] RUN cd /tmp && 	git clone git://github.com/xdebug/xdebug.git &&     	cd xdebug && 	git checkout xdebug_3_0 && 	phpize && 	./configure --enable-xdebug && 	make && 	make install &&     rm -rf /tmp/xdebug ;     { 	echo 'zend_extension=xdebug.so'; 	echo 'xdebug.mode=debug'; 	echo 'xdebug.client_port=9003'; 	
2022-07-05 22:56:01.782Z: echo 'xdebug.start_with_request = yes';   } > /usr/local/etc/php/conf.d/xdebug.ini;     docker-php-ext-enable xdebug;:
2022-07-05 22:56:01.800Z: ------
2022-07-05 22:56:01.818Z: executor failed running [/bin/sh -c cd /tmp && 	git clone git://github.com/xdebug/xdebug.git &&     	cd xdebug && 	git checkout xdebug_3_0 && 	phpize && 	./configure --enable-xdebug && 	make && 	make install &&     rm -rf /tmp/xdebug ;     { 	echo 'zend_extension=xdebug.so'; 	echo 'xdebug.mode=debug'; 	echo 'xdebug.client_port=9003'; 	echo 'xdebug.start_with_request = yes';   } > /usr/local/etc/php/conf.d/xdebug.ini;     docker-php-ext-enable xdebug;]: exit code: 1
2022-07-05 22:56:01.836Z: ERROR: Service 'wp' failed to build : Build failed
2022-07-05 22:56:01.853Z: Stop (326684 ms): Run: docker-compose --project-name vscode-wordpress -f /var/lib/docker/codespacemount/workspace/vscode-wordpress/docker-compose.yaml -f /var/lib/docker/codespacemount/workspace/vscode-wordpress/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml build
2022-07-05 22:56:01.871Z: Error: Command failed: docker-compose --project-name vscode-wordpress -f /var/lib/docker/codespacemount/workspace/vscode-wordpress/docker-compose.yaml -f /var/lib/docker/codespacemount/workspace/vscode-wordpress/.devcontainer/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml build
2022-07-05 22:56:01.888Z:     at $u (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:204:406)
2022-07-05 22:56:01.906Z:     at processTicksAndRejections (internal/process/task_queues.js:95:5)
2022-07-05 22:56:01.924Z:     at async RR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:204:2322)
2022-07-05 22:56:01.941Z:     at async PR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:188:2240)
2022-07-05 22:56:01.960Z:     at async zR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:2177)
2022-07-05 22:56:01.978Z:     at async nb (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:3110)
2022-07-05 22:56:01.996Z:     at async JR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:13046)
2022-07-05 22:56:02.019Z:     at async KR (/usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js:245:12802)
2022-07-05 22:56:02.032Z: Stop (328470 ms): Run: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/vscode-wordpress --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/vscode-wordpress/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-05 22:56:02.049Z: Exit code 1
2022-07-05 22:56:02.066Z: Failed to create container.
2022-07-05 22:56:02.085Z: Error: Command failed: /usr/bin/node /usr/lib/node_modules/@microsoft/vscode-dev-containers-cli/dist/spec-node/devContainersSpecCLI.js up --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --workspace-folder /var/lib/docker/codespacemount/workspace/vscode-wordpress --id-label Type=codespaces --log-level info --log-format json --config /var/lib/docker/codespacemount/workspace/vscode-wordpress/.devcontainer/devcontainer.json --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --remove-existing-container --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --skip-post-create --update-remote-user-uid-default never --mount-workspace-git-root false
2022-07-05 22:56:02.102Z: Error Code: 1302
2022-07-05 22:56:02.122Z: Container creation failed.
2022-07-05 22:56:02.147Z: 
2022-07-05 22:56:02.164Z: Creating recovery container.
```

**Comment by PiotrCzapla** [comment]
Thank you for reporting this. It seems that docker is not able to clone xdebug repo within the codespaces. It also takes ages to get the worspace up(8 mins) at least for my build.  It seems that it doesn't like 'git://' . Let me try to change that to https and we see.

**Comment by PiotrCzapla** [comment]
The change of protocol fixed the issue. There was another issue with CSS not loading due to additional reverseproxy in front of apache.  I've fixed it as well. Let me know if it works for you now.  It still takes ages to build but to fix that we would I would need to push my container to docker hub which has it's own issues.

**Comment by wuffo** [comment]
Yes, I can confirm that the container builds fine now. But we now arrive at the same problem that all the other wordpress developers face on codespaces: WP is not fully functional. I'll add it as a separate issue.
